//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarineInstitute
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarineEntities : DbContext
    {
        public MarineEntities()
            : base("name=MarineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catalogue> Catalogues { get; set; }
        public virtual DbSet<Datum> Data { get; set; }
        public virtual DbSet<ItemProp> ItemProps { get; set; }
        public virtual DbSet<SchemaTag> SchemaTags { get; set; }
        public virtual DbSet<StopWordList> StopWordLists { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vocabulary> Vocabularies { get; set; }
        public virtual DbSet<InsertDataTest> InsertDataTests { get; set; }
    }
}
