//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarineInstitute
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocabulary
    {
        public Vocabulary()
        {
            this.Catalogues = new HashSet<Catalogue>();
        }
    
        public int VocabID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Catalogue> Catalogues { get; set; }
    }
}
